version: '3.8'

services:
  extractor-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: extractor-ne:latest
    container_name: extractor-instancia
    # Forzamos el aislamiento de Hyper-V para evitar el error 0xc0370106
    isolation: hyperv
    ports:
      - "8000:8000"
    environment:
      # AQUÍ DEBES PEGAR TU API KEY REAL
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # Opcional: Configuración para que Python no guarde archivos .pyc
      - PYTHONDONTWRITEBYTECODE=1
    restart: always