/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedTercerosRouteImport } from './routes/_authenticated.terceros'
import { Route as AuthenticatedProductosRouteImport } from './routes/_authenticated.productos'
import { Route as AuthenticatedMiCuentaRouteImport } from './routes/_authenticated.mi-cuenta'
import { Route as AuthenticatedValidarExtraccionIndexRouteImport } from './routes/_authenticated.validar-extraccion.index'
import { Route as AuthenticatedValidarExtraccionExtractionIdRouteImport } from './routes/_authenticated.validar-extraccion.$extractionId'
import { Route as AuthenticatedTercerosTerceroIdRouteImport } from './routes/_authenticated.terceros.$terceroId'
import { Route as AuthenticatedSuperadminEmpresasRouteImport } from './routes/_authenticated.superadmin.empresas'
import { Route as AuthenticatedProductosProductoIdRouteImport } from './routes/_authenticated.productos.$productoId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated.admin.usuarios'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTercerosRoute = AuthenticatedTercerosRouteImport.update({
  id: '/terceros',
  path: '/terceros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductosRoute = AuthenticatedProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMiCuentaRoute = AuthenticatedMiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedValidarExtraccionIndexRoute =
  AuthenticatedValidarExtraccionIndexRouteImport.update({
    id: '/validar-extraccion/',
    path: '/validar-extraccion/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedValidarExtraccionExtractionIdRoute =
  AuthenticatedValidarExtraccionExtractionIdRouteImport.update({
    id: '/validar-extraccion/$extractionId',
    path: '/validar-extraccion/$extractionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTercerosTerceroIdRoute =
  AuthenticatedTercerosTerceroIdRouteImport.update({
    id: '/$terceroId',
    path: '/$terceroId',
    getParentRoute: () => AuthenticatedTercerosRoute,
  } as any)
const AuthenticatedSuperadminEmpresasRoute =
  AuthenticatedSuperadminEmpresasRouteImport.update({
    id: '/superadmin/empresas',
    path: '/superadmin/empresas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductosProductoIdRoute =
  AuthenticatedProductosProductoIdRouteImport.update({
    id: '/$productoId',
    path: '/$productoId',
    getParentRoute: () => AuthenticatedProductosRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/productos': typeof AuthenticatedProductosRouteWithChildren
  '/terceros': typeof AuthenticatedTercerosRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/productos/$productoId': typeof AuthenticatedProductosProductoIdRoute
  '/superadmin/empresas': typeof AuthenticatedSuperadminEmpresasRoute
  '/terceros/$terceroId': typeof AuthenticatedTercerosTerceroIdRoute
  '/validar-extraccion/$extractionId': typeof AuthenticatedValidarExtraccionExtractionIdRoute
  '/validar-extraccion/': typeof AuthenticatedValidarExtraccionIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/productos': typeof AuthenticatedProductosRouteWithChildren
  '/terceros': typeof AuthenticatedTercerosRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/productos/$productoId': typeof AuthenticatedProductosProductoIdRoute
  '/superadmin/empresas': typeof AuthenticatedSuperadminEmpresasRoute
  '/terceros/$terceroId': typeof AuthenticatedTercerosTerceroIdRoute
  '/validar-extraccion/$extractionId': typeof AuthenticatedValidarExtraccionExtractionIdRoute
  '/validar-extraccion': typeof AuthenticatedValidarExtraccionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/_authenticated/productos': typeof AuthenticatedProductosRouteWithChildren
  '/_authenticated/terceros': typeof AuthenticatedTercerosRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/productos/$productoId': typeof AuthenticatedProductosProductoIdRoute
  '/_authenticated/superadmin/empresas': typeof AuthenticatedSuperadminEmpresasRoute
  '/_authenticated/terceros/$terceroId': typeof AuthenticatedTercerosTerceroIdRoute
  '/_authenticated/validar-extraccion/$extractionId': typeof AuthenticatedValidarExtraccionExtractionIdRoute
  '/_authenticated/validar-extraccion/': typeof AuthenticatedValidarExtraccionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/mi-cuenta'
    | '/productos'
    | '/terceros'
    | '/admin/usuarios'
    | '/productos/$productoId'
    | '/superadmin/empresas'
    | '/terceros/$terceroId'
    | '/validar-extraccion/$extractionId'
    | '/validar-extraccion/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/mi-cuenta'
    | '/productos'
    | '/terceros'
    | '/'
    | '/admin/usuarios'
    | '/productos/$productoId'
    | '/superadmin/empresas'
    | '/terceros/$terceroId'
    | '/validar-extraccion/$extractionId'
    | '/validar-extraccion'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/_authenticated/mi-cuenta'
    | '/_authenticated/productos'
    | '/_authenticated/terceros'
    | '/_authenticated/'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/productos/$productoId'
    | '/_authenticated/superadmin/empresas'
    | '/_authenticated/terceros/$terceroId'
    | '/_authenticated/validar-extraccion/$extractionId'
    | '/_authenticated/validar-extraccion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terceros': {
      id: '/_authenticated/terceros'
      path: '/terceros'
      fullPath: '/terceros'
      preLoaderRoute: typeof AuthenticatedTercerosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos': {
      id: '/_authenticated/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mi-cuenta': {
      id: '/_authenticated/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof AuthenticatedMiCuentaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/validar-extraccion/': {
      id: '/_authenticated/validar-extraccion/'
      path: '/validar-extraccion'
      fullPath: '/validar-extraccion/'
      preLoaderRoute: typeof AuthenticatedValidarExtraccionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/validar-extraccion/$extractionId': {
      id: '/_authenticated/validar-extraccion/$extractionId'
      path: '/validar-extraccion/$extractionId'
      fullPath: '/validar-extraccion/$extractionId'
      preLoaderRoute: typeof AuthenticatedValidarExtraccionExtractionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terceros/$terceroId': {
      id: '/_authenticated/terceros/$terceroId'
      path: '/$terceroId'
      fullPath: '/terceros/$terceroId'
      preLoaderRoute: typeof AuthenticatedTercerosTerceroIdRouteImport
      parentRoute: typeof AuthenticatedTercerosRoute
    }
    '/_authenticated/superadmin/empresas': {
      id: '/_authenticated/superadmin/empresas'
      path: '/superadmin/empresas'
      fullPath: '/superadmin/empresas'
      preLoaderRoute: typeof AuthenticatedSuperadminEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos/$productoId': {
      id: '/_authenticated/productos/$productoId'
      path: '/$productoId'
      fullPath: '/productos/$productoId'
      preLoaderRoute: typeof AuthenticatedProductosProductoIdRouteImport
      parentRoute: typeof AuthenticatedProductosRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedProductosRouteChildren {
  AuthenticatedProductosProductoIdRoute: typeof AuthenticatedProductosProductoIdRoute
}

const AuthenticatedProductosRouteChildren: AuthenticatedProductosRouteChildren =
  {
    AuthenticatedProductosProductoIdRoute:
      AuthenticatedProductosProductoIdRoute,
  }

const AuthenticatedProductosRouteWithChildren =
  AuthenticatedProductosRoute._addFileChildren(
    AuthenticatedProductosRouteChildren,
  )

interface AuthenticatedTercerosRouteChildren {
  AuthenticatedTercerosTerceroIdRoute: typeof AuthenticatedTercerosTerceroIdRoute
}

const AuthenticatedTercerosRouteChildren: AuthenticatedTercerosRouteChildren = {
  AuthenticatedTercerosTerceroIdRoute: AuthenticatedTercerosTerceroIdRoute,
}

const AuthenticatedTercerosRouteWithChildren =
  AuthenticatedTercerosRoute._addFileChildren(
    AuthenticatedTercerosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedMiCuentaRoute: typeof AuthenticatedMiCuentaRoute
  AuthenticatedProductosRoute: typeof AuthenticatedProductosRouteWithChildren
  AuthenticatedTercerosRoute: typeof AuthenticatedTercerosRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedSuperadminEmpresasRoute: typeof AuthenticatedSuperadminEmpresasRoute
  AuthenticatedValidarExtraccionExtractionIdRoute: typeof AuthenticatedValidarExtraccionExtractionIdRoute
  AuthenticatedValidarExtraccionIndexRoute: typeof AuthenticatedValidarExtraccionIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMiCuentaRoute: AuthenticatedMiCuentaRoute,
  AuthenticatedProductosRoute: AuthenticatedProductosRouteWithChildren,
  AuthenticatedTercerosRoute: AuthenticatedTercerosRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedSuperadminEmpresasRoute: AuthenticatedSuperadminEmpresasRoute,
  AuthenticatedValidarExtraccionExtractionIdRoute:
    AuthenticatedValidarExtraccionExtractionIdRoute,
  AuthenticatedValidarExtraccionIndexRoute:
    AuthenticatedValidarExtraccionIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
