/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedTercerosRouteImport } from './routes/_authenticated.terceros'
import { Route as AuthenticatedProductosRouteImport } from './routes/_authenticated.productos'
import { Route as AuthenticatedPcpRouteImport } from './routes/_authenticated.pcp'
import { Route as AuthenticatedMiCuentaRouteImport } from './routes/_authenticated.mi-cuenta'
import { Route as AuthenticatedValidarExtraccionIndexRouteImport } from './routes/_authenticated.validar-extraccion.index'
import { Route as AuthenticatedTercerosIndexRouteImport } from './routes/_authenticated.terceros.index'
import { Route as AuthenticatedProductosIndexRouteImport } from './routes/_authenticated.productos.index'
import { Route as AuthenticatedPcpIndexRouteImport } from './routes/_authenticated.pcp.index'
import { Route as AuthenticatedValidarExtraccionExtractionIdRouteImport } from './routes/_authenticated.validar-extraccion.$extractionId'
import { Route as AuthenticatedTercerosTerceroIdRouteImport } from './routes/_authenticated.terceros.$terceroId'
import { Route as AuthenticatedSuperadminEmpresasRouteImport } from './routes/_authenticated.superadmin.empresas'
import { Route as AuthenticatedProductosProductoIdRouteImport } from './routes/_authenticated.productos.$productoId'
import { Route as AuthenticatedPcpImportsRouteImport } from './routes/_authenticated.pcp.imports'
import { Route as AuthenticatedPcpCatalogoRouteImport } from './routes/_authenticated.pcp.catalogo'
import { Route as AuthenticatedPcpPcpIdRouteImport } from './routes/_authenticated.pcp.$pcpId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated.admin.usuarios'
import { Route as AuthenticatedPcpConsultasConsultaIdRouteImport } from './routes/_authenticated.pcp.consultas.$consultaId'
import { Route as AuthenticatedPcpPcpIdRenglonesRenglonIdRouteImport } from './routes/_authenticated.pcp.$pcpId.renglones.$renglonId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTercerosRoute = AuthenticatedTercerosRouteImport.update({
  id: '/terceros',
  path: '/terceros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductosRoute = AuthenticatedProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPcpRoute = AuthenticatedPcpRouteImport.update({
  id: '/pcp',
  path: '/pcp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMiCuentaRoute = AuthenticatedMiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedValidarExtraccionIndexRoute =
  AuthenticatedValidarExtraccionIndexRouteImport.update({
    id: '/validar-extraccion/',
    path: '/validar-extraccion/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTercerosIndexRoute =
  AuthenticatedTercerosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTercerosRoute,
  } as any)
const AuthenticatedProductosIndexRoute =
  AuthenticatedProductosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductosRoute,
  } as any)
const AuthenticatedPcpIndexRoute = AuthenticatedPcpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPcpRoute,
} as any)
const AuthenticatedValidarExtraccionExtractionIdRoute =
  AuthenticatedValidarExtraccionExtractionIdRouteImport.update({
    id: '/validar-extraccion/$extractionId',
    path: '/validar-extraccion/$extractionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTercerosTerceroIdRoute =
  AuthenticatedTercerosTerceroIdRouteImport.update({
    id: '/$terceroId',
    path: '/$terceroId',
    getParentRoute: () => AuthenticatedTercerosRoute,
  } as any)
const AuthenticatedSuperadminEmpresasRoute =
  AuthenticatedSuperadminEmpresasRouteImport.update({
    id: '/superadmin/empresas',
    path: '/superadmin/empresas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductosProductoIdRoute =
  AuthenticatedProductosProductoIdRouteImport.update({
    id: '/$productoId',
    path: '/$productoId',
    getParentRoute: () => AuthenticatedProductosRoute,
  } as any)
const AuthenticatedPcpImportsRoute = AuthenticatedPcpImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AuthenticatedPcpRoute,
} as any)
const AuthenticatedPcpCatalogoRoute =
  AuthenticatedPcpCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedPcpRoute,
  } as any)
const AuthenticatedPcpPcpIdRoute = AuthenticatedPcpPcpIdRouteImport.update({
  id: '/$pcpId',
  path: '/$pcpId',
  getParentRoute: () => AuthenticatedPcpRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPcpConsultasConsultaIdRoute =
  AuthenticatedPcpConsultasConsultaIdRouteImport.update({
    id: '/consultas/$consultaId',
    path: '/consultas/$consultaId',
    getParentRoute: () => AuthenticatedPcpRoute,
  } as any)
const AuthenticatedPcpPcpIdRenglonesRenglonIdRoute =
  AuthenticatedPcpPcpIdRenglonesRenglonIdRouteImport.update({
    id: '/renglones/$renglonId',
    path: '/renglones/$renglonId',
    getParentRoute: () => AuthenticatedPcpPcpIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/pcp': typeof AuthenticatedPcpRouteWithChildren
  '/productos': typeof AuthenticatedProductosRouteWithChildren
  '/terceros': typeof AuthenticatedTercerosRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/pcp/$pcpId': typeof AuthenticatedPcpPcpIdRouteWithChildren
  '/pcp/catalogo': typeof AuthenticatedPcpCatalogoRoute
  '/pcp/imports': typeof AuthenticatedPcpImportsRoute
  '/productos/$productoId': typeof AuthenticatedProductosProductoIdRoute
  '/superadmin/empresas': typeof AuthenticatedSuperadminEmpresasRoute
  '/terceros/$terceroId': typeof AuthenticatedTercerosTerceroIdRoute
  '/validar-extraccion/$extractionId': typeof AuthenticatedValidarExtraccionExtractionIdRoute
  '/pcp/': typeof AuthenticatedPcpIndexRoute
  '/productos/': typeof AuthenticatedProductosIndexRoute
  '/terceros/': typeof AuthenticatedTercerosIndexRoute
  '/validar-extraccion/': typeof AuthenticatedValidarExtraccionIndexRoute
  '/pcp/consultas/$consultaId': typeof AuthenticatedPcpConsultasConsultaIdRoute
  '/pcp/$pcpId/renglones/$renglonId': typeof AuthenticatedPcpPcpIdRenglonesRenglonIdRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/pcp/$pcpId': typeof AuthenticatedPcpPcpIdRouteWithChildren
  '/pcp/catalogo': typeof AuthenticatedPcpCatalogoRoute
  '/pcp/imports': typeof AuthenticatedPcpImportsRoute
  '/productos/$productoId': typeof AuthenticatedProductosProductoIdRoute
  '/superadmin/empresas': typeof AuthenticatedSuperadminEmpresasRoute
  '/terceros/$terceroId': typeof AuthenticatedTercerosTerceroIdRoute
  '/validar-extraccion/$extractionId': typeof AuthenticatedValidarExtraccionExtractionIdRoute
  '/pcp': typeof AuthenticatedPcpIndexRoute
  '/productos': typeof AuthenticatedProductosIndexRoute
  '/terceros': typeof AuthenticatedTercerosIndexRoute
  '/validar-extraccion': typeof AuthenticatedValidarExtraccionIndexRoute
  '/pcp/consultas/$consultaId': typeof AuthenticatedPcpConsultasConsultaIdRoute
  '/pcp/$pcpId/renglones/$renglonId': typeof AuthenticatedPcpPcpIdRenglonesRenglonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/_authenticated/pcp': typeof AuthenticatedPcpRouteWithChildren
  '/_authenticated/productos': typeof AuthenticatedProductosRouteWithChildren
  '/_authenticated/terceros': typeof AuthenticatedTercerosRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/pcp/$pcpId': typeof AuthenticatedPcpPcpIdRouteWithChildren
  '/_authenticated/pcp/catalogo': typeof AuthenticatedPcpCatalogoRoute
  '/_authenticated/pcp/imports': typeof AuthenticatedPcpImportsRoute
  '/_authenticated/productos/$productoId': typeof AuthenticatedProductosProductoIdRoute
  '/_authenticated/superadmin/empresas': typeof AuthenticatedSuperadminEmpresasRoute
  '/_authenticated/terceros/$terceroId': typeof AuthenticatedTercerosTerceroIdRoute
  '/_authenticated/validar-extraccion/$extractionId': typeof AuthenticatedValidarExtraccionExtractionIdRoute
  '/_authenticated/pcp/': typeof AuthenticatedPcpIndexRoute
  '/_authenticated/productos/': typeof AuthenticatedProductosIndexRoute
  '/_authenticated/terceros/': typeof AuthenticatedTercerosIndexRoute
  '/_authenticated/validar-extraccion/': typeof AuthenticatedValidarExtraccionIndexRoute
  '/_authenticated/pcp/consultas/$consultaId': typeof AuthenticatedPcpConsultasConsultaIdRoute
  '/_authenticated/pcp/$pcpId/renglones/$renglonId': typeof AuthenticatedPcpPcpIdRenglonesRenglonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/mi-cuenta'
    | '/pcp'
    | '/productos'
    | '/terceros'
    | '/admin/usuarios'
    | '/pcp/$pcpId'
    | '/pcp/catalogo'
    | '/pcp/imports'
    | '/productos/$productoId'
    | '/superadmin/empresas'
    | '/terceros/$terceroId'
    | '/validar-extraccion/$extractionId'
    | '/pcp/'
    | '/productos/'
    | '/terceros/'
    | '/validar-extraccion/'
    | '/pcp/consultas/$consultaId'
    | '/pcp/$pcpId/renglones/$renglonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/mi-cuenta'
    | '/'
    | '/admin/usuarios'
    | '/pcp/$pcpId'
    | '/pcp/catalogo'
    | '/pcp/imports'
    | '/productos/$productoId'
    | '/superadmin/empresas'
    | '/terceros/$terceroId'
    | '/validar-extraccion/$extractionId'
    | '/pcp'
    | '/productos'
    | '/terceros'
    | '/validar-extraccion'
    | '/pcp/consultas/$consultaId'
    | '/pcp/$pcpId/renglones/$renglonId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/_authenticated/mi-cuenta'
    | '/_authenticated/pcp'
    | '/_authenticated/productos'
    | '/_authenticated/terceros'
    | '/_authenticated/'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/pcp/$pcpId'
    | '/_authenticated/pcp/catalogo'
    | '/_authenticated/pcp/imports'
    | '/_authenticated/productos/$productoId'
    | '/_authenticated/superadmin/empresas'
    | '/_authenticated/terceros/$terceroId'
    | '/_authenticated/validar-extraccion/$extractionId'
    | '/_authenticated/pcp/'
    | '/_authenticated/productos/'
    | '/_authenticated/terceros/'
    | '/_authenticated/validar-extraccion/'
    | '/_authenticated/pcp/consultas/$consultaId'
    | '/_authenticated/pcp/$pcpId/renglones/$renglonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terceros': {
      id: '/_authenticated/terceros'
      path: '/terceros'
      fullPath: '/terceros'
      preLoaderRoute: typeof AuthenticatedTercerosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos': {
      id: '/_authenticated/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pcp': {
      id: '/_authenticated/pcp'
      path: '/pcp'
      fullPath: '/pcp'
      preLoaderRoute: typeof AuthenticatedPcpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mi-cuenta': {
      id: '/_authenticated/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof AuthenticatedMiCuentaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/validar-extraccion/': {
      id: '/_authenticated/validar-extraccion/'
      path: '/validar-extraccion'
      fullPath: '/validar-extraccion/'
      preLoaderRoute: typeof AuthenticatedValidarExtraccionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terceros/': {
      id: '/_authenticated/terceros/'
      path: '/'
      fullPath: '/terceros/'
      preLoaderRoute: typeof AuthenticatedTercerosIndexRouteImport
      parentRoute: typeof AuthenticatedTercerosRoute
    }
    '/_authenticated/productos/': {
      id: '/_authenticated/productos/'
      path: '/'
      fullPath: '/productos/'
      preLoaderRoute: typeof AuthenticatedProductosIndexRouteImport
      parentRoute: typeof AuthenticatedProductosRoute
    }
    '/_authenticated/pcp/': {
      id: '/_authenticated/pcp/'
      path: '/'
      fullPath: '/pcp/'
      preLoaderRoute: typeof AuthenticatedPcpIndexRouteImport
      parentRoute: typeof AuthenticatedPcpRoute
    }
    '/_authenticated/validar-extraccion/$extractionId': {
      id: '/_authenticated/validar-extraccion/$extractionId'
      path: '/validar-extraccion/$extractionId'
      fullPath: '/validar-extraccion/$extractionId'
      preLoaderRoute: typeof AuthenticatedValidarExtraccionExtractionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terceros/$terceroId': {
      id: '/_authenticated/terceros/$terceroId'
      path: '/$terceroId'
      fullPath: '/terceros/$terceroId'
      preLoaderRoute: typeof AuthenticatedTercerosTerceroIdRouteImport
      parentRoute: typeof AuthenticatedTercerosRoute
    }
    '/_authenticated/superadmin/empresas': {
      id: '/_authenticated/superadmin/empresas'
      path: '/superadmin/empresas'
      fullPath: '/superadmin/empresas'
      preLoaderRoute: typeof AuthenticatedSuperadminEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos/$productoId': {
      id: '/_authenticated/productos/$productoId'
      path: '/$productoId'
      fullPath: '/productos/$productoId'
      preLoaderRoute: typeof AuthenticatedProductosProductoIdRouteImport
      parentRoute: typeof AuthenticatedProductosRoute
    }
    '/_authenticated/pcp/imports': {
      id: '/_authenticated/pcp/imports'
      path: '/imports'
      fullPath: '/pcp/imports'
      preLoaderRoute: typeof AuthenticatedPcpImportsRouteImport
      parentRoute: typeof AuthenticatedPcpRoute
    }
    '/_authenticated/pcp/catalogo': {
      id: '/_authenticated/pcp/catalogo'
      path: '/catalogo'
      fullPath: '/pcp/catalogo'
      preLoaderRoute: typeof AuthenticatedPcpCatalogoRouteImport
      parentRoute: typeof AuthenticatedPcpRoute
    }
    '/_authenticated/pcp/$pcpId': {
      id: '/_authenticated/pcp/$pcpId'
      path: '/$pcpId'
      fullPath: '/pcp/$pcpId'
      preLoaderRoute: typeof AuthenticatedPcpPcpIdRouteImport
      parentRoute: typeof AuthenticatedPcpRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pcp/consultas/$consultaId': {
      id: '/_authenticated/pcp/consultas/$consultaId'
      path: '/consultas/$consultaId'
      fullPath: '/pcp/consultas/$consultaId'
      preLoaderRoute: typeof AuthenticatedPcpConsultasConsultaIdRouteImport
      parentRoute: typeof AuthenticatedPcpRoute
    }
    '/_authenticated/pcp/$pcpId/renglones/$renglonId': {
      id: '/_authenticated/pcp/$pcpId/renglones/$renglonId'
      path: '/renglones/$renglonId'
      fullPath: '/pcp/$pcpId/renglones/$renglonId'
      preLoaderRoute: typeof AuthenticatedPcpPcpIdRenglonesRenglonIdRouteImport
      parentRoute: typeof AuthenticatedPcpPcpIdRoute
    }
  }
}

interface AuthenticatedPcpPcpIdRouteChildren {
  AuthenticatedPcpPcpIdRenglonesRenglonIdRoute: typeof AuthenticatedPcpPcpIdRenglonesRenglonIdRoute
}

const AuthenticatedPcpPcpIdRouteChildren: AuthenticatedPcpPcpIdRouteChildren = {
  AuthenticatedPcpPcpIdRenglonesRenglonIdRoute:
    AuthenticatedPcpPcpIdRenglonesRenglonIdRoute,
}

const AuthenticatedPcpPcpIdRouteWithChildren =
  AuthenticatedPcpPcpIdRoute._addFileChildren(
    AuthenticatedPcpPcpIdRouteChildren,
  )

interface AuthenticatedPcpRouteChildren {
  AuthenticatedPcpPcpIdRoute: typeof AuthenticatedPcpPcpIdRouteWithChildren
  AuthenticatedPcpCatalogoRoute: typeof AuthenticatedPcpCatalogoRoute
  AuthenticatedPcpImportsRoute: typeof AuthenticatedPcpImportsRoute
  AuthenticatedPcpIndexRoute: typeof AuthenticatedPcpIndexRoute
  AuthenticatedPcpConsultasConsultaIdRoute: typeof AuthenticatedPcpConsultasConsultaIdRoute
}

const AuthenticatedPcpRouteChildren: AuthenticatedPcpRouteChildren = {
  AuthenticatedPcpPcpIdRoute: AuthenticatedPcpPcpIdRouteWithChildren,
  AuthenticatedPcpCatalogoRoute: AuthenticatedPcpCatalogoRoute,
  AuthenticatedPcpImportsRoute: AuthenticatedPcpImportsRoute,
  AuthenticatedPcpIndexRoute: AuthenticatedPcpIndexRoute,
  AuthenticatedPcpConsultasConsultaIdRoute:
    AuthenticatedPcpConsultasConsultaIdRoute,
}

const AuthenticatedPcpRouteWithChildren =
  AuthenticatedPcpRoute._addFileChildren(AuthenticatedPcpRouteChildren)

interface AuthenticatedProductosRouteChildren {
  AuthenticatedProductosProductoIdRoute: typeof AuthenticatedProductosProductoIdRoute
  AuthenticatedProductosIndexRoute: typeof AuthenticatedProductosIndexRoute
}

const AuthenticatedProductosRouteChildren: AuthenticatedProductosRouteChildren =
  {
    AuthenticatedProductosProductoIdRoute:
      AuthenticatedProductosProductoIdRoute,
    AuthenticatedProductosIndexRoute: AuthenticatedProductosIndexRoute,
  }

const AuthenticatedProductosRouteWithChildren =
  AuthenticatedProductosRoute._addFileChildren(
    AuthenticatedProductosRouteChildren,
  )

interface AuthenticatedTercerosRouteChildren {
  AuthenticatedTercerosTerceroIdRoute: typeof AuthenticatedTercerosTerceroIdRoute
  AuthenticatedTercerosIndexRoute: typeof AuthenticatedTercerosIndexRoute
}

const AuthenticatedTercerosRouteChildren: AuthenticatedTercerosRouteChildren = {
  AuthenticatedTercerosTerceroIdRoute: AuthenticatedTercerosTerceroIdRoute,
  AuthenticatedTercerosIndexRoute: AuthenticatedTercerosIndexRoute,
}

const AuthenticatedTercerosRouteWithChildren =
  AuthenticatedTercerosRoute._addFileChildren(
    AuthenticatedTercerosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedMiCuentaRoute: typeof AuthenticatedMiCuentaRoute
  AuthenticatedPcpRoute: typeof AuthenticatedPcpRouteWithChildren
  AuthenticatedProductosRoute: typeof AuthenticatedProductosRouteWithChildren
  AuthenticatedTercerosRoute: typeof AuthenticatedTercerosRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedSuperadminEmpresasRoute: typeof AuthenticatedSuperadminEmpresasRoute
  AuthenticatedValidarExtraccionExtractionIdRoute: typeof AuthenticatedValidarExtraccionExtractionIdRoute
  AuthenticatedValidarExtraccionIndexRoute: typeof AuthenticatedValidarExtraccionIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMiCuentaRoute: AuthenticatedMiCuentaRoute,
  AuthenticatedPcpRoute: AuthenticatedPcpRouteWithChildren,
  AuthenticatedProductosRoute: AuthenticatedProductosRouteWithChildren,
  AuthenticatedTercerosRoute: AuthenticatedTercerosRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedSuperadminEmpresasRoute: AuthenticatedSuperadminEmpresasRoute,
  AuthenticatedValidarExtraccionExtractionIdRoute:
    AuthenticatedValidarExtraccionExtractionIdRoute,
  AuthenticatedValidarExtraccionIndexRoute:
    AuthenticatedValidarExtraccionIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
